spring.application.name=school-managment

# Database Configuration
spring.datasource.url=jdbc:postgresql://ep-hidden-recipe-abccfnut-pooler.eu-west-2.aws.neon.tech:5432/neondb?sslmode=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_GFnLOjJEMN36

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000



